@address = 192.168.0.71:80

# Get complete json doc
GET http://{{address}}/json HTTP/1.1
content-type: application/json

###

# Set name
POST http://{{address}}/settings/ui?DS=Plattenspieler1 HTTP/1.1
Content-Type: xapplication/x-www-form-urlencoded

### 

# Enable light
POST http://{{address}}/json/state HTTP/1.1
content-type: application/json

{
    "on": true
}

###

# Get effects list
GET http://{{address}}/json/eff HTTP/1.1
content-type: application/json

###

# Set solid white color
POST http://{{address}}/json HTTP/1.1
content-type: application/json

{
  "bri": 255,
  "seg": [
    {
      "fx": 0,
      "col": [
        [255,255,255]
      ]
    }
  ]
}

###

# Set effect, brightness and speed
POST http://{{address}}/json HTTP/1.1
content-type: application/json

{
  "bri": 10,
  "seg": [
    {
      "fx": 9,
      "sx": 100
    }
  ]
}