@address = 192.168.0.71:80

# Get complete json doc
GET http://{{address}}/json HTTP/1.1
content-type: application/json

###

# Set name
POST http://{{address}}/settings/ui?DS=Plattenspieler HTTP/1.1
content-type: xapplication/x-www-form-urlencoded

### 

# Enable light
POST http://{{address}}/json/state HTTP/1.1
content-type: application/json

{
    "on": true
}

###

# Get effects list
GET http://{{address}}/json/eff HTTP/1.1
content-type: application/json

###

# Set solid color
POST http://{{address}}/json HTTP/1.1
content-type: application/json

{
  "seg": [
    {
      "col": [
        [0,255,200]
      ]
    }
  ]
}

###

# Set effect, brightness and speed
POST http://{{address}}/json HTTP/1.1
content-type: application/json

{
  "bri": 10,
  "seg": [
    {
      "fx": 3,
      "sx": 100
    }
  ]
}